---
title: Rのセットアップ
---

## Rのインストール

### 基本的な流れ

Windowsだと、以下の流れとなります:

1. R-baseのダウンロード
2. Rtoolsのダウンロード
3. R-baseのインストール
4. Rtoolsのインストール

Macだと、以下の流れとなります:

1. R-baseのダウンロード
2. R-baseのインストール
3. Xcodeのインストール

### Windowsマシンへのインストール

#### R-baseのダウンロード {#base-dl-win}

まず、https://www.r-project.org にアクセスし、"CRAN"にアクセスします。その後、近いミラーサイトか、Cloudのサイトを選択してください。

CRANについたら、**Download R for Windows**へのリンクをクリックし、まずは**base**をクリックします。表示されたら、トップに**Download R 3.3.1 for Windows**(2016/07/12現在)をクリックし、ダウンロードしてください。

#### Rtoolsのダウンロード

一つ戻り、"R for Windows"のページから、**Rtools**のリンクをクリックします。表示されたら、**Rtools34.exe**(2016/07/12現在)のリンクをクリックしてダウンロードしてください。

#### base、Rtoolsのインストール

まず先に、ダウンロードしたbaseのファイルをダブルクリックして実行してください。インストールは基本そのまま進めてもらっても大丈夫だと思います。その後でRtoolsをダブルクリックして実行してください。こちらもそのまま進んでもらって大丈夫かと思います。

### Macへのインストール

#### Rのダウンロード・インストール

上述のCRANのサイトから、**Download R for (Mac) OS X**をクリックします。表示されたら、**R-3.3.1.pkg**(2016/07/12現在)をクリックしてダウンロードしてください。ダウンロードしたファイルを実行し、Rをインストールしてください。

#### Xcodeのインストール

MacのApp Storeを開き、Xcodeをダウンロードしてインストールしてください。もしすでにXcodeをインストールしている場合は、最新版かどうかを確認してください。ただ、非常に重たくて時間がかかるので、ひとまずであれば後回しでも構いません。

## RStudioのインストール

https://www.rstudio.com へアクセスし、**Products**→**RStudio**へ進みます。少しスクロールして、**DOWNLOAD RSTUDIO DESKTOP**(Free版)をクリックしてください。あとは自分のOS版をダウンロードして、インストールしてください。

## Rの初期設定

基本RStudioで使っていくので、気をつけるところだけ:

### デフォルトの作業ディレクトリ(working directory)について

作業ディレクトリは、要するに「Rの作業スペース」で、そこにいろいろなファイル(隠しも含む)が作られていきます。RStudioであらかじめデフォルトの作業ディレクトリを設定しておくのをおすすめします:

1. RStudioを開く
2. メニューの**Tools** - **Global Options...**を選択
3. **General**の一番上のところで設定

<div class="panel panel-warning">
  <div class="panel-heading">ディレクトリパスと日本語について</div>
  <div class="panel-body">
  作業ディレクトリまでのパスに日本語が入っていると、RStudioはうまく動きません。**Rを使うとき、ファイル名やディレクトリ名は半角で使いましょう**。
  
  特にWindowsユーザーの場合、**ユーザーアカウントが日本語で登録していると面倒なことに**なります。Cなどのドライブ直下に作業ディレクトリを設置するか、それでもうまく行かない場合は別アカウントを準備することを考えてみてください。それも厳しいなら、仮想マシンを立ててみるという手段もあります。
  </div>
</div>

### その他の設定について

設定しておくと楽なことなどはありますが、もう少し慣れてからでいいと思います。

[ページのトップへ](#)